### PR TITLE
Cr add attraction detail

### PR DESCRIPTION
**Pull request by CheoR**
# Description

Add button to hide/unhide details on click.
Moved event listeners.

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

`git fetch --all`
`git checkout cr-add-attraction-detail`
`serve`

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by daprieu — APPROVED** [review]
looks good no issues on my end

**Review by Daniel-L-Ross — APPROVED** [review]
The show/hide button worked as expected. Looking good!

**Review by samj0516 — DISMISSED** [review]
love the emoji's in your details!

**Review by samj0516 — APPROVED** [review]
lewks gewd

**Review by daprieu — APPROVED** [review]
got my approval

**Review by Daniel-L-Ross — APPROVED** [review]
💯

**Pull request merged**
