### PR TITLE
made some css for weath

### PR DESCRIPTION
**Pull request by daprieu**
# Description

Let me know whether or not you like the weather

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by CheoR — APPROVED** [review]
Weather icons render nicely on mobile view.

Much like.

**Review by samj0516 — DISMISSED** [review]
Looks great, I dig it :)

**Review by CheoR — CHANGES_REQUESTED** [review]
`<div>
    `
`

Latest change still showing img tag missing closing angle bracket.

**Review by samj0516 — APPROVED** [review]
lewks gewd

**Review by CheoR — APPROVED** [review]
Everything looks good.

**Review by Daniel-L-Ross — APPROVED** [review]
Weather looks good in mobile. The weather 'day cards' need some adjustment in desktop view.

**Pull request merged**
