### PR TITLE
Cr save to json

### PR DESCRIPTION
**Pull request by CheoR**
# Description

Save button active when user makes 3 selections. 
Save selections to db.json as object with selection names as keys.
`
let itinerary = {

      parkName: partkName,

      eateryName: eateryName,

      attractionName: attractionName
}
`

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

`git fetch --all`
`git checkout cr-save-to-json`
`serve`

In other terminal

`json-server -p 8088 -w db.json`

View itinerary at

` http://localhost:8088/itineraries`

- By default, save button should be disabled.
- User makes 3 selections and button should turn green.
- If user changes one or more selections to the default value, button is disabled again.
- If user makes 3 selections and saves, button turns blue and selections are saved to db.json
- If user makes 3 selections, saves, and selects a default option, button is disabled.
- If user makes 3 selections, saves, and makes another valid selection, button turns from blue to green.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings or errors
- [] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Daniel-L-Ross — DISMISSED** [review]
After the last commit I have full save functionality. NICE!

**Review by daprieu — CHANGES_REQUESTED** [review]
so it seems that your code works If all you do is make the 3 selections then hit Save 

But if you change your mind before hitting Save 

And make new selections it records and copies all of the times you make a new selection from the dropdown.

Then when you hit Save it populates every drop down change that you made into the api.

**Review by daprieu — APPROVED** [review]

**Review by daprieu — DISMISSED** [review]

**Review by samj0516 — APPROVED** [review]
good job

**Review by daprieu — APPROVED** [review]

**Review by samj0516 — APPROVED** [review]
we're almost done!

**Pull request merged**
